### ISSUE TITLE
How can I get the torch_enzyme and tf_enzyme

### ISSUE THREAD

**Issue by GinFungYJF** [wsmoses/Enzyme#125]
Hi, how can I get the torch_enzyme and tf_enzyme described in the paper? It seems that they have not been open-sourced?

**Comment by wsmoses** [comment]
They're both open sourced, but substantially less polished than the main Enzyme and Enzyme.jl repos.

They're here (https://github.com/wsmoses/Enzyme-Pytorch) for PyTorch and (https://github.com/wsmoses/Enzyme-TF) for TensorFlow.

Specifically both repos have hardcoded paths (such as here: https://github.com/wsmoses/Enzyme-Pytorch/blob/5e3d2673bfeb8ac1aee7f9bd201f9340ecc9fe65/cpp/lltm.cpp#L73) and call external processes rather than using PyBind to call Enzyme directly. Thus I wouldn't recommend calling them right now unless you're willing to do at least a little bit of hacking.

Which framework are you hoping to use? We can spend some time in the coming week to try writing the relevant docs and make the integrations nicer.

Likewise we welcome pull requests both for docs (the www branch here hosts enzyme.mit.edu), the integrations, and everything else.
