### ISSUE TITLE
Can Enzyme handle virtual functions?

### ISSUE THREAD

**Issue by mplxrg** [wsmoses/Enzyme#316]
Hi,
I tried to call a virtual function inside the function to be differentiated but got the wrong result. It seems that Enzyme is not able to handle runtime polymorphism. I was wondering if there is a way to deal with virtual functions?

**Comment by wsmoses** [comment]
Can you provide an example of the issue? We do support various styles of virtual functions with caveats that the underlying virtual function has to fall back to assuming all arguments are active, and have expected type conventions

**Comment by mplxrg** [comment]
I am trying to differentiate a high level function of a relatively complex project, it involves many virtual function calls. I boil down the code to a simpler version below.

```cpp
#include <iostream>
#include <Eigen/Dense>

using namespace std;

void __enzyme_autodiff(...);

template <typename... Args>
void __enzyme_autodiff(void *, Args...);

int enzyme_dup, enzyme_const, enzyme_out, enzyme_dupnoneed;

struct Object
{
    virtual double eval(Eigen::VectorXd &v) = 0;
};

struct Object1 : Object
{
    double eval(Eigen::VectorXd &v)
    {
        return val * v.sum();
    }
    double val;
};

struct Object2 : Object
{
    double eval(Eigen::VectorXd &v)
    {
        return val + v.sum();
    }
    double val;
};

double eval(Object &o, Eigen::VectorXd &v)
{
    return o.eval(v);
}

void deval(Object &o, Object &d_o, Eigen::VectorXd &v, Eigen::VectorXd &dv)
{
    __enzyme_autodiff((void *)(eval),
                      enzyme_dup, &o, &d_o,
                      enzyme_dup, &v, &dv);
}

int main()
{
    Eigen::VectorXd v = Eigen::VectorXd::Ones(10);
    Eigen::VectorXd dv(10);
    Object *o = new Object1();
    double s = eval(*o, v);
    cout << s << endl;
    Object *d_o = new Object1();
    deval(*o, *d_o, v, dv);
    cout << dv << endl;
}
```

The code could pass compilation but would  cause Segmentation fault (core dumped) at runtime.

I wondered if there is any documentation or examples on virtual functions, since I couldn't find any except one sentence in the paper:

> If you want Enzyme to differentiate a function with a virtual C++ class as an argument, however, you need to pass in a modiﬁed virtual method table in the shadow that conforms with Enzyme’s calling convention.

**Comment by wsmoses** [comment]
Ah so you're passing the virtual object in as a parameter -- in which case then yes that sentence from the paper applies here.

In essence if the virtual object is created within the function being differentiated, then Enzyme will create the corresponding differentiated method table. If, as in this case, you're passing in the virtual object as a parameter Enzyme assumes that it matches its convention, which for the shadow has {forward pass, reverse pass}* where the virtual method is. Since you pass in a regular object instead of this massaged convention, you get the segfault when it tries to unpack the forward/reverse pass out of an object which does not contain the forward/reverse.

Do you mind explaining a bit more about the end code and how/why you're using virtual functions. For example, the easiest solution would be calling it in such a way that you didn't need to pass virtual functions as parameters (but instead make virtual functions/object within the function being differentiated). In the background I'll think about how to make a helper function that will make creating the correct virtual method table easier to do at the C++ level.

**Comment by mplxrg** [comment]
Actually, I am trying to integrate Enzyme into a differentiable rendering project. Currently, I have a render function `render(Scene &, double *image)`, and I want to differentiate this high level function somehow. The Scene object contains pointers to Shapes, Emitters, and BSDFs, etc. These pointers are all pointing to base classes. In the derived class, there are some differentiable parameters. As for The Scene object, it is assembled at runtime outside the render function.

Also, can you explain more on "pass in a modiﬁed virtual method table in the shadow that conforms with Enzyme’s calling convention"?  I am not sure how to code this. Thanks!

**Comment by wsmoses** [comment]
Expanding upon this a bit (and clearly we should add this to the documentation, and also add a magic C++ wrapper function for creating these), suppose you have something like the following (using C-style to make the virtual methods explicit):

```
struct S {
   double (*fn)(double);
   double val;
}

double foo(struct S* s) {
  return s->fn(s->val);
}

double square(double x){ return x * x; }

void primal() {
  struct S s;
  s.fn = square;
  s.val = 3.0;
  printf("%f\n", foo(&s));
}
```

To create the modified virtual method table here, one would need to do something like the following:

```
// The convention for the forward pass is to return
//   a) the original return
//   b) the shadow return, if the return type is duplicated [e.g. pointer]
//   c) a tape containing all values cached from fwd to reverse, if the call isn't able to be deduced statically (as is the case here with a virtual function call), this will be a void*, otherwise it is a tuple of all values needing caching in that function.
struct DoubleAndTape {
    double x;
    void* tape;
};

DoubleAndTape __enzyme_augmentfwd(void*, double);
DoubleAndTape fwdsquare(double x) {
    return __enzyme_augmentfwd((void*)square, x);
}
double __enzyme_reverse(void*, double, double, void*);
double revsquare(double x, double differet, void* tape) {
    return __enzyme_reverse((void*)square, x, differet, tape);
}
void* shadow_sq[2] = {(void*)fwdsquare, (void*)revsquare};
void __enzyme_autodiff(void*, void*, void*);
void reverse() {
  struct S s;
  s.fn = square;
  s.val = 3.0;
  struct S d_s;
  d_s.fn = (double (*)(double))shadow_sq;
  d_s.val = 0.0;
  __enzyme_autodiff((void*)foo, &s, &d_s);
  printf("shadow res=%f\n", d_s.val);
}
```

(note that to run the above, if the virtual function returns a value, you need a patch to `__enzyme_reverse` here: https://github.com/wsmoses/Enzyme/pull/317 )

**Comment by wsmoses** [comment]
In the case of the C++ virtual function in your example, the correct convention for the shadow requires setting the virtual method table of the shadow pointer, to contain the augmented forward/reverse pass method tuple like above.

The "create the augmented method pointer" definitely can have some syntax sugar added along the lines of:
```
  // No crazy struct types, or extra calls required.
  d_s.fn = __enzyme_virtualtuple(square);
```

I'll need to think about this a bit more to simplify the C++ virtual method table syntax. Ideally, I'm thinking something like the following but I'm not sure how to make it work yet. It can of course still be done manually using the proposed `__enzyme_virtualtuple` being called for all methods in the vtable (or the super manual version above).
```
Object* d_obj = ...;
__enzyme_virtualtable(Object1, d_obj);
```

**Comment by wsmoses** [comment]
Also note that you don't need to use `__enzyme_reverse` and friends to generate the forward/reverse pass of the virtual method, but you can put whatever definition you'd like (and it would essentially be treated like a custom derivative being registered).

**Comment by wsmoses** [comment]
First part of syntactic sugar should land here: https://github.com/wsmoses/Enzyme/pull/318

**Comment by mplxrg** [comment]
Thank you so much for such a detailed explanation! For the C++ example I gave, I'm still confused about how to modify the vtable manually since I haven't done this before. From the C example you gave, setting the virtual function pointer of the shadow seems to be done at runtime. Does this mean I need to know the layout of the vtable and the address of virtual function pointers? Also, generating the forward and reverse pass for the **member function** seems to require some additional work. Do you mind give one more example using C++ virtual functions? Thanks!

**Comment by wsmoses** [comment]
Yeah, this is sufficiently into the weeds and platform dependent that I wanted to get you a slightly higher level version rather than have you manually hack everything.

This is still platform dependent and quite finnicky, but look at this code (which should work on that branch): https://github.com/wsmoses/Enzyme/blob/vfunc2/enzyme/test/Integration/ReverseMode/virtualshadow3.cpp

In essence if the ABI is to store the vtable in a pointer-sized object at the start, this should work. It does also require being run right after construction and at least at O1 optimization (so that the argument to `__enzyme_virtualreverse` isn't an opaque load, but a cast of the actual vtable). Note that I ran this on macos, and added some of the ABI specific stuff I saw on my installation, but since vtable's are quite implementation dependant, I foresee plenty of additional ABI' needing to be added (which ought be easy to do).

Additionally note here that it is unsafe to use the shadow object's virtual functions since their ABI will have been replaced. I'm also can forsee the automatic vtable fixup not playing nicely with destructors, so something to look out for.

**Comment by mplxrg** [comment]
Thanks for the example! I tried to play with `__enzyme_virtualreverse` on vtable. It seems that the example below works. However, in the Object1::eval(Vector &), I switch to the code in the comment, the enzyme pass would fail. The same thing happened to Object2::eval(Vector &). I am not sure if this issue relates to ABI or something else. Could you take a look? Thanks!

```cpp
#include <stdio.h>
#include <Eigen/Dense>

typedef Eigen::Vector3d Vector;

void __enzyme_autodiff(...);

template <typename... Args>
double __enzyme_autodiff(void *, Args...);

template <typename T>
T __enzyme_virtualreverse(T);

int enzyme_dup, enzyme_const, enzyme_out, enzyme_dupnoneed;

struct Object
{
    virtual Vector eval(Vector &v) = 0;
    Vector val;
};

struct Object1 : Object
{
    Vector eval(Vector &v)
    {
        return val * v.sum();
        // return val;
    }
};

struct Object2 : Object
{
    Vector eval(Vector &v)
    {
        return val + v;
        // return v;
    }
};

double eval(Object &o, Vector &v)
{
    return o.eval(v).sum();
}

void deval(Object &o, Object &d_o, Vector &v, Vector &d_v)
{
    __enzyme_autodiff((void *)(eval),
                      enzyme_dup, &o, &d_o,
                      enzyme_dup, &v, &d_v);
}

int main()
{
    Vector v = Vector(10., 10., 10.);
    Vector d_v;
    Object *o = new Object1();
    Object *d_o = new Object1();
    *((void **)d_o) = __enzyme_virtualreverse(*(void **)d_o);
    double res;
    deval(*o, *d_o, v, d_v);
    printf("d_o->val: %f, %f, %f\n", d_o->val[0], d_o->val[1], d_o->val[2]);
    printf("d_v: %f, %f, %f\n", d_v[0], d_v[1], d_v[2]);

    v = Vector(10., 10., 10.);
    d_v = Vector();
    o = new Object2();
    d_o = new Object2();
    *((void **)d_o) = __enzyme_virtualreverse(*(void **)d_o);
    deval(*o, *d_o, v, d_v);
    printf("d_o.val: %f, %f, %f\n", d_v[0], d_v[1], d_v[2]);
    printf("d_v: %f, %f, %f\n", d_v[0], d_v[1], d_v[2]);
}
```

**Comment by wsmoses** [comment]
Having not looked at this deeply, can you set d_v to Vector(0., 0., 0.)

**Comment by mplxrg** [comment]
I tried, but it didn't work.

**Comment by wsmoses** [comment]
Ah sorry you mean theres a compile time error rather than a runtime error. Can you upload the output of the compilation?

**Comment by mplxrg** [comment]
Here is the compilation output: [compile.log](https://github.com/wsmoses/Enzyme/files/7103018/compile.log)

**Comment by wsmoses** [comment]
What happens if you add `-mllvm -enzyme-loose-types`

**Comment by mplxrg** [comment]
I tried to add the flag, but the code still can't compile. It output the same error.

**Comment by mplxrg** [comment]
I think I found the problem. The return type of the virtual function cannot be duplicated. If I modify the code as below, the code would work.
```cpp
struct Object1 : Object
{
   void eval(Vector &v, Vector &res)
    {
        res = val * v.sum();
        // res = val;
    }
};
```

**Comment by wsmoses** [comment]
Using the following command line args works for the code:
```
wmoses@beast:~/git/Enzyme/enzyme/build12 (vfunc2) $ /mnt/pci4/wmdata/llvm12/build/bin/clang++ erev.cpp -Xclang -load -Xclang Enzyme/ClangEnzyme-12.so  -O2 -Xclang -new-struct-path-tbaa
```

In essence what is happening here is that Enzyme cannot deduce the type of the copy within eval, since it isn't used and Clang doesn't emit type information. The `-new-struct-path-tbaa` flag in Clang appears to remedy this TBAA info, resulting in success.
